export const firebaseAuthErrors = {
  "auth/claims-too-large": "Claims payload exceeds 1000 bytes",
  "auth/email-already-exists": "Email already in use",
  "auth/email-already-in-use": "Email already in use",
  "auth/id-token-expired": "ID token expired",
  "auth/id-token-revoked": "ID token revoked",
  "auth/insufficient-permission": "Insufficient permission",
  "auth/internal-error": "Unexpected server error",
  "auth/invalid-argument": "Invalid argument provided",
  "auth/invalid-claims": "Invalid custom claim attributes",
  "auth/invalid-continue-uri": "Invalid continue URL",
  "auth/invalid-creation-time": "Invalid creation time",
  "auth/invalid-credential": "Invalid credentials",
  "auth/invalid-disabled-field": "Invalid disabled user property",
  "auth/invalid-display-name": "Invalid display name",
  "auth/invalid-dynamic-link-domain": "Invalid dynamic link domain",
  "auth/invalid-email": "Invalid email address",
  "auth/invalid-email-verified": "Invalid email verified property",
  "auth/invalid-hash-algorithm": "Invalid hash algorithm",
  "auth/invalid-hash-block-size": "Invalid hash block size",
  "auth/invalid-hash-derived-key-length": "Invalid derived key length",
  "auth/invalid-hash-key": "Invalid hash key",
  "auth/invalid-hash-memory-cost": "Invalid hash memory cost",
  "auth/invalid-hash-parallelization": "Invalid hash parallelization",
  "auth/invalid-hash-rounds": "Invalid hash rounds",
  "auth/invalid-hash-salt-separator": "Invalid salt separator",
  "auth/invalid-id-token": "Invalid ID token",
  "auth/invalid-last-sign-in-time": "Invalid last sign-in time",
  "auth/invalid-page-token": "Invalid page token",
  "auth/invalid-password": "Invalid password",
  "auth/invalid-password-hash": "Invalid password hash",
  "auth/invalid-password-salt": "Invalid password salt",
  "auth/invalid-phone-number": "Invalid phone number",
  "auth/invalid-photo-url": "Invalid photo URL",
  "auth/invalid-provider-data": "Invalid provider data",
  "auth/invalid-provider-id": "Invalid provider ID",
  "auth/invalid-oauth-responsetype": "Invalid OAuth response type",
  "auth/invalid-session-cookie-duration": "Invalid session cookie duration",
  "auth/invalid-uid": "Invalid UID",
  "auth/invalid-user-import": "Invalid user record to import",
  "auth/maximum-user-count-exceeded": "Maximum user count exceeded",
  "auth/missing-android-pkg-name": "Missing Android Package Name",
  "auth/missing-continue-uri": "Missing continue URL",
  "auth/missing-hash-algorithm": "Missing hash algorithm",
  "auth/missing-ios-bundle-id": "Missing iOS Bundle ID",
  "auth/missing-uid": "Missing UID",
  "auth/missing-oauth-client-secret": "Missing OAuth client secret",
  "auth/operation-not-allowed": "Sign-in provider disabled",
  "auth/phone-number-already-exists": "Phone number already in use",
  "auth/project-not-found": "Firebase project not found",
  "auth/reserved-claims": "Reserved custom user claims",
  "auth/session-cookie-expired": "Session cookie expired",
  "auth/session-cookie-revoked": "Session cookie revoked",
  "auth/too-many-requests": "Too many requests",
  "auth/uid-already-exists": "UID already in use",
  "auth/unauthorized-continue-uri": "Unauthorized continue URL domain",
  "auth/user-not-found": "User not found",
};
